name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-build:
    name: test build
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install libblkid-dev
      run: |
        sudo apt-get update
        sudo apt-get install libblkid-dev
    - name: Run tests
      run: ./test
    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.48.0
        args: -E=gofmt --timeout=30m0s
  test-validate:
    name: test ignition-validate
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Build ignition-validate
      shell: bash
      run: go build -o ignition-validate github.com/coreos/ignition/v2/validate
    - name: Test ignition-validate
      shell: bash
      run: |
        go test -timeout 60s -cover \
            $(go list ./config/... ./validate/...) --race
